### ISSUE TITLE
Material Tab - ngIf Side Effects

### ISSUE THREAD

**Issue by charliem** [dart-lang/angular_components#140]
The Material Tab uses ngIf as the mechanism to show and hide the tab's content. Whilst this works fine for a lot of cases it does have side effects. Specifically, if a tab contains an iFrame its contents are refreshed when the tab switches. This wipes out any changes made in the iFrame every time you switch tabs.

To work around this we produced a local fork which used CSS to change the display to none (leaving the tabs contents in the DOM but hidden). This appeared to work without issue. I appreciate there are performance benefits of using ngIf. Could a property not be added to control the hiding mechanism of the tab?

**Comment by TedSander** [comment]
I don't think we want to bake this into material-tab itself, but good news is angular and this component makes it pretty easy to subclass material-tab and have it have different behavior. For instance you could write

```dart
@Component(
    selector: 'material-hidden-tab',
    host: const {
      'role': 'tabpanel',
      '[attr.id]': 'panelId',
      '[attr.aria-labelledby]': 'tabId',
      '[class.material-tab]': 'active',
    },
    providers: const [
      const Provider(Tab, useExisting: MaterialHiddenTabComponent),
    ],
    template: '''
        <div class="tab-content" [class.active]="active">
          <ng-content></ng-content>
        </div>''',
    styleUrls: const ['package:angular_components/src/components/material_tab/material_tab.scss.css'])
class MaterialHiddenTabComponent extends MaterialHiddenTabComponent {
   MaterialHiddenTabComponent(HtmlElement element, @Optional() IdGenerator idGenerator)
      : super(element, idGenerator);
}
```

We will be moving the host properties to annotations so that would be one less thing to copy. Really that means that just the style url, and the constructor would be the only things that are adding a bit of boilerplate.

You could even mix and match the different behaviors. Here is an example

```html
<material-tab-panel>
    <material-hidden-tab label="tab 1">
      <iframe src="some_content.html"></iframe>
    </material-hidden-tab>
    <material-tab label="tab 2">
    <template deferredContent>
      Tab #2 Contents
    </template>
  </material-tab>
</material-tab-panel>
```
