### ISSUE TITLE
Indeterminate material progress animation issue

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/angular_components#166]
The material progress is giving me an unexpected animation. See what I mean here (video):
https://photos.app.goo.gl/Ek4jk35I8avlfa3M2

The template code is lifted straight form the example:
```
<material-progress [indeterminate]="true"></material-progress>
```

**Comment by TedSander** [comment]
Interesting. What platform/browser is this happening on?

**Comment by jimmyff** [comment]
OSX 10.11.6 : Chromium, Chrome, Firefox
Android 8 : Chrome

As it's affecting every browser I've tried I'm assuming there could be some style overlap?

I've temporairly made it appear on my app so you can see here: https://goo.gl/6Jwpka

**Comment by zacharydenton** [comment]
I've seen a similar issue before. In that case, the <material-progress> was initialized too soon, before the width of the progress bar could be determined (e.g. the parent element was set to display: none). The <material-progress> needs to know the width in order to perform the animation correctly - otherwise the animation will look like what you posted.

Can you modify the app so that the <material-progress> element has the correct width when it's initialized?

**Comment by jimmyff** [comment]
I added an `*ngIf` so the modal would only be created when required but this still hasn't resolved the issue (without the updated release). This is the template code:

```
<modal *ngIf="showConnectionDialog" [visible]="showConnectionDialog">
  <material-dialog info class="basic-dialog">

    <div header>
      <h3>Connection issue</h3>
    </div>

    <div style="padding:1em 0;">
    <p>
      We're having difficulty connecting, please check your device is connected to the internet. Attempting to reconnect...
    </p>
    </div>

    <div footer style="padding:0 1em;">
        <material-progress [indeterminate]="true"></material-progress>
    </div>

  </material-dialog>
</modal>
```

If the next release resolves the problem then by all means close this issue and I'll sit tight!

**Comment by nshahan** [comment]
@zacharydenton landed a change internally so that the animation will fall back to a non-optimized animation if the width is 0 after view init. The non-optimized animation will adjust itself when the width changes. 

This change will get captured in the next sync I land externally, which I'm working on and should be coming soon. It will be dependent on the newest angular 5.0.0-alpha release though.

**Comment by nshahan** [comment]
The version that supports angular: 5.0.0-alpha has been published and the fallback animation is present. https://pub.dartlang.org/packages/angular_components/versions/0.9.0-alpha
