### ISSUE TITLE
Make material-input type can dynamic change by code

### ISSUE THREAD

**Issue by joo** [dart-lang/angular_components#171]
Sample:
```
<material-input label="{{labelName}}" type="{{inputType}}"></material-input>
```

**Comment by alescdb** [comment]
Not sure but this should work, no?
`<material-input [label]="labelName" [type]="inputType"></material-input>`

**Comment by zoechi** [comment]
@alescdb there is no difference between these to, because both bind string values. `{{}}` can only bind strings, while `[]` can bind any value type.

**Comment by TedSander** [comment]
So we do this specifically because the type is hooked up to specific directives/validators/accessors. We think the API would be confusing and poor if the some of the types worked dynamically, but others didn't.

For example: type='number' and type='percent' has different code associated with them, and the directives can't be added removed from the component dynamically. Also you couldn't write a selector for a dynamic input where the number input could be set.

For internal users this hasn't been too much of an issue as it isn't a common practice to need to change the type of an input since changing the type can greatly affect the API/use of that input. Code dealing with a number is a good amount different from text for instance.

The workaround for this is to use NgSwitch or NgIf to change between different types.

**Comment by joo** [comment]
Thanks @TedSander ,  "NgSwitch or NgIf " work fine.
