### ISSUE TITLE
Split angular_components into two - angular_components_base and material_components

### ISSUE THREAD

**Issue by pratikpparikh** [dart-lang/angular_components#201]
Dear Owners and Contributors,

It is only me or does it seems that angular_components have a lot of goodies (button_directive, content, dynamic_component, focus, forms, framework_stabilizers, model, util -  just some that comes to mind, maybe some depreciation as there seems some overlapping functionality) that deserve a right to have its own package so it is separate from material_components and layout.   This will allow others to build there own material design components rather than using what is provided don't get me wrong the out of the box is great.  But this will keep the reusable code more easy to consume without pulling in material components.

Regards,
Pratik Parikh

**Comment by adaojunior** [comment]
Similar concept can be found on Angular TS: [Angular Material CDK](https://github.com/angular/material2/tree/master/src/cdk).

**Comment by nshahan** [comment]
Yes, this has been something I have considered for a while. As of yet I haven't seen a scenario where moving these to a separate package would add a lot of value to the ecosystem.

I am open to the idea but curious what you would like to avoid when importing the angular_components. 

Some issues I've been considering:
* The angular_components and a hypothetical "base utilities" package would be very tightly coupled. They would also have similar dependencies. 
  * I don't think you would avoid bringing on many transitive dependencies by avoiding importing the angular_components package.
  * The each version of the components would likely be locked to a version of the "base utilities" package since internally these are developed as one. This could make mixing and matching different components more difficult.

* I was considering this more when all of the code was in the lib/src/ directory. Now that we have exposed the entry points many of these files are accessible. You can import them and dart2js tree shaking should limit the size increase in your app to the files you are using.

**Comment by pratikpparikh** [comment]
Hi Nicholas,

The reason for submitting this request is not to avoid transitive dependencies as I was already aware of dart tree shaking and how it can help in reducing the branch path usage while generating the js code.  The request has more to do with getting started, if the code is better separated it makes it clear to follow, understand, utilize, maintain, contribute too.  Also, most organizations will like to have clear control over there UX patterns and components because that is what makes their application interaction unique.  They can still follow a material design style guide but might end up building there own set of component library.  Also, I see better value in robust behavior library then the component library.  If AngularDart has better behavior library then components will be easy to develop and put together.  Just some of the reason why I was requesting this issue.  Hope this helps and is justified.       

Regards,
Pratik Parikh

**Comment by nshahan** [comment]
Thanks for the feedback. At this time I don't think there are enough compelling reasons to break this into separate packages at the cost of an increased support burden.
