### ISSUE TITLE
Input - cannot bind to Type property

### ISSUE THREAD

**Issue by sudolibre** [dart-lang/angular_components#210]
Because type is an attribute binding that's injected into the constructor you cannot bind to this property to change the type dynamically. It would be ideal if we could do something like this:
```[type]="isPasswordVisible ? 'text' ? 'password'"``` 
This works with native input elements

This is required for the common use case of creating a visibility icon on the right of a password field to toggle masking of the entered text.

**Comment by TedSander** [comment]
Type is used in the selectors to provide different directives or in some cases components for the the element. These can't change dynamically and as such we can't have the type change dynamically.

The work around is to use an ng-if and have two separate instances that can change depending on the type you would like to use. Understand this makes it harder, but there is very little chance we will be changing this.

**Comment by sudolibre** [comment]
Okay understood. I would like to say that password unmasking is crucial for UX and the lack of such a feature has been linked to users making more errors, degrading a users feeling of confidence, and encouraging less secure passwords. This is easily achievable with the native element. The material-input effectively demotes this to a second-class feature. I hope this is not solely to piggy-back on the existing type property.

**Comment by TedSander** [comment]
There is actually another simple workaround using a directive.

```dart
@Directive(selector: 'material-input[showPassword]')
class MaterialInputShowPasswordDirective {
  MaterialInputComponent input;
  MaterialInputShowPasswordDirective(this.input);

  @Input()
  set showPassword(bool unhide) {
    input.type = unhide ? 'text' : 'password';
  }
}
```

Sorry if there is an error. I just freehanded the code.

**Comment by sudolibre** [comment]
Awesome i'll look into this and maybe see if the example team would add this to the examples. Thanks for taking the extra time to help.

**Comment by zreptil** [comment]
I stumbled across this issue and looked at different places for a solution. Still the directive seems to be the only way to solve this. But I was not happy with the solution, since the control that is handled by this directive doesn't show the changes immediately. I had to focus the input to make the change visible. 

So I searched for a different way to have the control updated. The best solution for me was the following:

```
@Directive(selector: 'material-input[showPassword]')
class MaterialInputShowPasswordDirective {
  MaterialInputComponent input;
  MaterialInputShowPasswordDirective(this.input);

  @Input()
  set showPassword(bool unhide) {
    input.type = unhide ? 'text' : 'password';
    input.trailingText = unhide ? " " : "";
  }
}

```

I added a change to the trailingText since I rarely use this. I didn't want to change the display of the control, so this seems the best way for me.

But I am wondering, why this is still a problem that needs a not so easy solution. In my eyes this is a very common usecase that should be handled by the controls with simply setting an attribute or property. For material-controls it would even be good to have a clickable Icon that switches the visibility, enabled with a simple attribute.

I tried to derive from material-input to create such a control by myself, but I could not make it work. So this solution seems still to be the only one that is working. And I thought, I share my improvement to it with others, that stumble in the same issue.

Thanks to @TedSander for this very useful solution :)
