### ISSUE TITLE
material-menu API documentation not found

### ISSUE THREAD

**Issue by supermuka** [dart-lang/angular_components#217]
`material-menu`  (`package:angular_components/material_menu/material_menu.dart`) API documentation not found in https://www.dartdocs.org/documentation/angular_components/0.9.0-alpha/index.html.

**Comment by nshahan** [comment]
This is due to the automatic doc generator tool not ignoring the missing generated files that will be available once the package is built. We added the ignore to our analysis_options.yaml file so our package doesn't fail on analysis. There was discussion started here but AFAIK there wasn't any progress yet. #207

**Comment by nshahan** [comment]
The gallery is now the first place I'd look for documentation and live examples showing how to use the components.
https://dart-lang.github.io/angular_components_example/

The docs are now being generated correctly, but they are not as easy to navigate.
https://pub.dartlang.org/documentation/angular_components/0.9.0-alpha+11/material_menu_material_menu/MaterialMenuComponent-class.html
