### ISSUE TITLE
DateTimePickerComponent should update binding when only Date but no time was selected

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_components#237]
When the user only selects a date but doesn't select a time the `dateTimeChange` event is not triggered and the model doesn't get updated. 

When the time is optional, the user should not need to chose one and 00:00 should be assumed.

Is there a way to achieve this?

**Comment by zacharydenton** [comment]
We don't currently support making the time optional in material-date-time-picker, but it seems like something we could support in the future. The original intention was that it should be used if you need a DateTime (i.e. both date and time). We also have separate material-datepicker and material-time-picker components.

**Comment by yuandong** [comment]
In current date material-date-time-picker, required setting are applied to both date and time picker.
When the date-time-picker set to required, if user only selects a date but doesn't select a time, event is not triggered because time is ambiguous.
When the date-time-picker set to optional, if user only selects a date but doesn't select a time, event is triggered with NULL value, this is used in the case that user clear out time then date to return to not-set.

It's a great suggestion to set a default time when date is picked and time is not set no matter material-date-time-picker is required or optional. The default time will be 00:00 when there's no restriction or earliest possible time if minDateTime is set. 
Does it work for your case? We can update the code to support it. With this proposed change, event will alway be triggered when user pick a date because there's no ambiguity for the time part now.

**Comment by TedSander** [comment]
Sorry what is the use case for using material-date-time-picker when you just want the date? Why not just use material-datepicker?

@yuandong @zacharydenton is the lead for the date/time picker components. So any changes would need to be approved by him.

**Comment by zoechi** [comment]
@TedSander The user should be able to select a time, but usually the time doesn't matter and just 00:00 should be used as @yuandong suggested

**Comment by TedSander** [comment]
@yuandong sorry I didn't recognize your username. Yes please work with Zach to add this change if you have time.

**Comment by yuandong** [comment]
SGTM. I'll work with Zach and add the change this/early next week.

**Comment by nshahan** [comment]
Feature added in 40631ac52cfb80dbc6bcd96c8cd5f4c5f97ea224.
