### ISSUE TITLE
How can I get notify if data of material-date-time-picker changed?

### ISSUE THREAD

**Issue by EasonPai** [dart-lang/angular_components#277]
Event `dateTimeChange` for ` material-date-time-picker` can be found in source
https://github.com/dart-lang/angular_components/blob/master/lib/material_datepicker/material_date_time_picker.dart

so I tried this
`<material-date-time-picker (dateTimeChange)="onUpdate()" [(dateTime)]="dateTime" [required]="true">
</material-date-time-picker>`

and capture with this
`
  void onUpdate() {
    sDate = dateTime.toString();
  }
`

But, when I run app, I get errors like:
`
GET http://localhost:63142/main.ddc.js 500 (Internal Server Error)
  req.load	
  load	
  load	
  fetch	
  check	
  enable	
  enable	
  (anonymous function)	
  (anonymous function)	
  each	
  enable	
  init	
  (anonymous function)	
Refused to execute script from 'http://localhost:63142/main.ddc.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
Uncaught Error: Script error for "web/main"
  makeError	
  onScriptError	
GET http://localhost:63142/main.ddc.js.errors 500 (Internal Server Error)
  requirejs.onError	
  onError	
  onScriptError	
Unknown error loading http://localhost:63142/main.ddc.js
  xhr.onreadystatechange
`

So, what is the correct way to get notifications of data changed ?

**Comment by TedSander** [comment]
You get the MIME error anytime the app doesn't compile.

In this case the compile error is:

Found multiple events with the same name: dateTimeChange. You should merge the handlers into a single statement.

This is because `[(dateTime)]="dateTime"` is equivalent to `[dateTime]="dateTime" (dateTimeChange)="dateTime = $event"`

There are two ways around this:
a) Put everything in your `onUpdate` function:
`[dateTime]="dateTime" (dateTimeChange)="onUpdate($event)"`
` void onUpdate(dateTime) { sDate = dateTime.toString(); }`

b) Use a setter for dateTime in the controller to capture the string value:
`[(dateTime)]="dateTime"`
`set dateTime(value) { _dateTime = value; sDate = value.toString(); }`

**Comment by EasonPai** [comment]
Cool, the second way is even better than what I expected.
Thanks for such a thoroughly explanation.
