### ISSUE TITLE
AngularDart equivalent of Angular Flex-Layout?

### ISSUE THREAD

**Issue by Brahmasmi** [dart-lang/angular_components#357]
These may very well be stupid questions, but nevertheless:

1) What is the AngularDart equivalent of Angular Flex-Layout [1] ?
2) If there is one, could you please point to examples and/or samples?
3) If there is none (or only Google-internal), could you please share examples of the mechanisms / techniques typically used to achieve the functionality of Flex-Layout? Also, if there is a Google-internal one, would it be possible to share it externally?

Thanks.

[1] - https://github.com/angular/flex-layout

**Comment by TedSander** [comment]
As far as I know there isn't one. It isn't an ask that comes up internally, and teams don't find a need for this kind of library.

We also believe that having this many directives and code effecting these properties can easily create applications that are unperformant. Especially at the size of apps we build internally.

Instead we just change the classes, or styling directly on the elements, and components using binding expressions. Using this strategy we don't really get feedback that they would need this, especially for the cost involved.

**Comment by Brahmasmi** [comment]
Thank you @TedSander for your response.

I am still trying to learn Dart, so forgive me for asking, but could you please point me to some example/samples/usage/documentation of the binding expressions mechanism for responsive layout of components?

Dhanyavaad.

**Comment by TedSander** [comment]
Basically I am talking about using

`<div [style.order]="2"></div>`

or more often since we find playing with the individual styles harder to maintain:
`<div [class.smallScreen]="isSmallScreen"></div>`

Where smallScreen has styling logic just for the small screen.

That being said our philosophy is to try to have as much of the styling outside of angularDart and Dart as possible because it slows things down a lot. If we can do it with CSS only we will.
