### ISSUE TITLE
[Feature Request]Override sass variables/support inject_assets_builder

### ISSUE THREAD

**Issue by manuscle** [dart-lang/angular_components#391]
Overriding values from sass files seems to not be possible easily. Using ::ng-deep everywhere is not really convenient way.
A solution could be to use the [inject_assets_builder](https://pub.dartlang.org/packages/inject_assets_builder) package.
But to do this, you need to support inject_assets_builder

**Comment by pschiffmann** [comment]
To provide some more context: I wrote the `inject_assets_builder` package because at the company I work for, we have written our own components package that we reuse in different customer projects. These projects usually need to be styled to match the customers corporate identity, so we have to override some css values like colors in every single component. Angular provides the `::ng-deep` selector for this purpose, which is great if you only want to style certain subtrees of an app; but unnecessarily verbose if you want to override **all** colors/border-radius/etc. in the whole app. That's what `inject_assets_builder` is good for.

With this package, we can add a file `lib/_variables.default.scss` to our components package in which we define variables and default values (e.g. `$my-package-text-primary: $mat-text-primary`), but application packages can just inject their own file that sets `$my-package-text-primary` to a different value. Because all component .scss files import the injected file, the new color is used in all components without the need to define sass mixins, and without using `::ng-deep` at all.

**Comment by nshahan** [comment]
That is an interesting package to solve this particular scenario. It doesn't work for our use cases internally because the component leaf package needs to be buildable and cacheable without any information from the consuming application. For this reason I don't think we could realistically support this but I am curious.

@pschiffmann Do you have a fork of angular_components that shows the changes you made to get it working?

**Comment by pschiffmann** [comment]
> Do you have a fork of angular_components that shows the changes you made to get it working?

We didn't fork angular_components (our designer doesn't like material design ...)
We have a package with components `<bar-chart>`, `<user-box>`, `dynamic-page-content>`, etc.

I can't share that code with you, but I uploaded a minimal working example that demonstrates how to use the builder in [this repo](https://github.com/pschiffmann/inject_assets_example).
The repo contains two packages, `my_components`, which can be used as a dependency, and `my_app`, which provides the overridden sass variables. `my_components|lib/_variables.default.scss` is a fallback file that gets used when the consuming package doesn't inject another file. Which file should be injected is configured in `my_app|build.yaml`.
If you `webdev serve` the `my_app` package, you can see that the sass values from `my_app|lib/_variables.scss` are used in `my_components|lib/color_box/color_box_component.scss`, even though `my_components` doesn't have a dependency on `my_app`.

> It doesn't work for our use cases internally because the component leaf package needs to be buildable and cacheable without any information from the consuming application.

With leaf package you mean `angular_components`? As you can see, *right now* the `build` package can handle my builder. The build is correctly cached, invalidated and rebuilt when you change `my_app|lib/_variables.scss`.

When I wrote the package, I asked @jakemac53 (who significantly helped me with debugging) whether it is good practice to inject files from a consumer package into a dependency package. He said (I'm paraphrasing): "This works in package:build, but it wouldn't work in Bazel. But right now, they are not actively working on Bazel compatibility, and if it enables use cases like mine, it'd be worth to keep it."

**Comment by TedSander** [comment]
Internally our build system is basically Bazel. Jake's comments were in response to only the outside world not to the inside world. Anything we use has to work both inside and outside, and so sadly we can't do something like this.

**Comment by pschiffmann** [comment]
Even if you add support for `inject_asset_builder`, an application must explicitly opt in to it (as I do in my example [here](https://github.com/pschiffmann/inject_assets_example/blob/master/my_app/build.yaml)). If an application doesn't, `angular_components` will work exactly like it does today.
It also doesn't try to replace the mixin API you have in place already; if I'm not mistaken, they can co-exist without interfering with each other.
So, implementing this would not be a breaking change. You couldn't use it in your Bazel builds, but it wouldn't affect your builds either.

That being said, I respect your decision if you don't want to maintain the additional complexity for a feature you know you won't use.

**Comment by TedSander** [comment]
It is very much the maintenance burden of adding the additional complexity. Especially something that internal testing/development is not going to catch any errors or bugs that may occur.
