### ISSUE TITLE
MaterialDatepickerComponent internationalisation

### ISSUE THREAD

**Issue by parnham** [dart-lang/angular_components#394]
The placeholder text used in the datepicker component uses the Intl package to provide translations. However our application uses its own translation layer where the translations are stored server-side and can be updated by clients at runtime to match their needs. 

In the MaterialDateRangePickerComponent the ```placeHolderMsg``` is an input which would allow us to override the Intl provided message with our own - however this input does not exist for MaterialDatepickerComponent. This also presents inconsistencies in the APIs for the different date picker components.

Is it possible to make the standard datepicker work in a similar way to the date range picker?

**Comment by TedSander** [comment]
We aren't going to provide an Input for every message that we have in a component. Intl is the standard way for us to provide messages and each Input lowers the performance of the component, and makes maintenance harder. Sometimes we have an Input because a product/spec required flexibility, but we aren't going to add Inputs everywhere in every case.
