### ISSUE TITLE
where is "drawer" declared?

### ISSUE THREAD

**Issue by crushman1** [dart-lang/angular_components#397]
hi im pretty new to angularDart however i am from a flutter background. i'm trying to understand the material app drawer example. in that example you mention the class "drawer" and at some point it calls a function drawer.toggle(). but no where in the documentation does it say where this class is created or instantiated. 
I mean i can create the class myself and create the function "toggle()" but is that what i am suppose to do or is this class already create somewhere in the example. if so, where is it?

**Comment by TedSander** [comment]
This is called a varRef in angular (they might use a different name for it, but that is what I learned it as.)

In a template you can mark something with the # symbol and then use it later in the template. Additionally since that might be ambiguous you can say which directive you want to grab. In this case the drawer directive.

In the examples you should see `#drawer="drawer"`. This is saying please set the drawer variable to be the directive that is exported as `drawer`. You can then use this variable elsewhere in the template like when the button is pressed to toggle the drawer.
