### ISSUE TITLE
User Story (docs): Material Theme Editor to Angular Components

### ISSUE THREAD

**Issue by MateusAmin** [dart-lang/angular_components#398]
I am a software engineer new to Dart, Angular, and Material design. My learning path went like this:

Material Design -> Material Theme Editor -> Dart -> Dart Angular ->  Angular Components

I am not sure what the best way of connecting the designs I made with Sketch(Material Theme Editor) to Angular:

Material Theme Editor -> Angular Components

I am not an experience frontend engineer and without a good amount of guidance I probably will not produce the optimal solution. I see that theming support is an open and ongoing issue. But I really just want some hand holding to get from point A to B so I can copy solid well thought out patterns. Regardless of any short comings.

It would be nice to have one cohesive story. Like if you converted the Tour of Heroes to angular components using a theme specified in the Material Design docs. The Lottery Tour is good introduction but doesn't include to customization.

Currently, I get the sense I should use ng-deep and override the /css/ stuff in the root component. And then, override the component stuff where applicable. I see that there probably isn't not a smooth way to do this given the sass structure. For example, error-color:

https://github.com/dart-lang/angular_components/search?q=error-color&unscoped_q=error-color

It seems to me to be a simple question of mapping with a little bit of how. I generate SASS from the Material Theme Editor and map it to my angular/angular-components app.

Regardless, this stack/framework has been great for me and is a big boon. Thanks for all your efforts!

**Comment by TedSander** [comment]
You should be using the mixins to override the style as needed. They are the ones that use ::ng-deep for example: https://github.com/dart-lang/angular_components/blob/c644746d2824df7cfaf0a34f900b1f8557caddbc/angular_components/lib/material_button/_mixins.scss#L249

It is a good idea to connect this to the sketch tool, but we will not be supporting it. Internally we don't use this tool, and we can only use the mixins for theming due to our build system (bazel.)

Sorry it isn't easier but this is the best we are going to provide. Glad you like using the stack.
