### ISSUE TITLE
Buttons on cards wrapped in a repeating ng-container lose their functionality

### ISSUE THREAD

**Issue by DanielSmith1239** [dart-lang/angular_components#404]
Hello. I'm attempting to have a repeating card inside a ng-container, however the buttons inside the card lose the "material" appearance (ink ripples on click for example), as well as their functionality (unable to call a function on click). When I place a single card outside the container, the buttons work perfectly. For the cards, I'm using the example code from the AngularDart gallery.

**Comment by TedSander** [comment]
Sorry I don't have enough context. Can you add the dart and template code that you have? The minimal amount to repo would be appreciated. Otherwise we can't be too much help

**Comment by DanielSmith1239** [comment]
Here is an example of what I'm trying to do:
```
<ng-container *ngFor="let cat of tabs">
        <material-tab label="{{cat}}">
          <div class="container">
            <p *ngIf="cardsForCat(cat).length == 0">No cards to display.</p>
            <div *ngIf="cardsForCat(cat).length > 0">
              <ng-container *ngFor="let row of cardsForCat(cat)">
                <div class="row">
                  <ng-container *ngFor="let card of row">
                    <div class="col"> 
                      <div class="mdc-card mdc-card--outlined demo-size">
    <div class="mdc-card__media mdc-card__media--16-9 demo-card__media"></div>
    <div class="demo-card__primary">
      <h2 class="demo-card__title">Our Changing Planet</h2>
      <h3 class="demo-card__subtitle">by Kurt Wagner</h3>
    </div>
    <div class="demo-card__secondary">
      Visit ten places on our planet that are undergoing the biggest changes today.
    </div>
    <div class="mdc-card__actions">
      <div class="mdc-card__action-buttons">
        <material-button>Read</material-button>
        <material-button>Bookmark</material-button>
      </div>
      <div class="mdc-card__action-icons">
        <material-button icon>
          <material-icon icon="favorite_border"></material-icon>
        </material-button>
        <material-button icon>
          <material-icon icon="share"></material-icon>
        </material-button>
        <material-button icon>
          <material-icon icon="more_vert"></material-icon>
        </material-button>
      </div>
    </div>
  </div>
                    </div>
                  </ng-container>
                </div>
              </ng-container>
            </div>
          </div>
        </material-tab>
      </ng-container>
```

When I have a single card outside of the loop they look fine, however they don't work as expected when inside the loop.

**Comment by DanielSmith1239** [comment]
@TedSander any tips?

**Comment by TedSander** [comment]
Can you show the code for cardsForCat and tabs?

I suspect you are recreating the elements in your for loop every single digest loop. It is very important that you keep the iterables stable (they aren't creating completely new contents each digest loop.)

For example:
`cardsForCat(_) => [Card(1), Card(2), Card(3)];`
Super bad!!! List and cards are getting created each digest loop. Which is recreating all your html above each and every time.

This might highlight it a bit more:
`cardsForCat(_) => [new Card(1), new Card(2), new Card(3)];`

Angular uses identity know if something has changed. So even if your object looks the same to you angular might be re-creating everything because the instance of the item in the collection has changed. One way around this is to use trackBy but it is better to just keep the list stable.

**Comment by DanielSmith1239** [comment]
I think that’s my problem. The function involves mapping a different list of objects, and returns that map. I’ll try a different way of handling everything that involves just keeping stable iterables, and I’ll post an update. Thanks!

**Comment by DanielSmith1239** [comment]
I changed up the code to use a stable iterable, however now the loop is not updating the contents when the iterable is changed. How do I make sure it changes?

Sorry if this is a dumb question, I'm a new to Angular Dart.

**Comment by TedSander** [comment]
So for standard angular it is going to trigger a change when the input variables identity changes. This means it is a new object for objects, and a different value for primitives. Now ng-for works a bit differently because people like to use the same collection, but want it to change the elements when elements are added or removed from the collection. In this case ngFor doesn't care if the iterable identity changes, but will trigger when the immediate children's identity changes. Now if your changes are happening deeper in that child you will need to re-create the child for the ngFor loop to be triggered again. Another way to do this is to use trackBy in ngFor and having the identity passed back for the child to change.

**Comment by nshahan** [comment]
For reference: https://webdev.dartlang.org/angular/guide/template-syntax#ngfor-with-trackby
