### ISSUE TITLE
Meta issue: Expose our SASS theming API to end-users

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular_components#45]

**Comment by nshahan** [comment]
My proposal at the moment:

## Phase 1
I am currently planning on adding the sass files to this repo and the pub package. Users will need a version of sass installed to build the package. Importing one of the included scss files in custom user created scss file would require getting the path of the package fetched by `pub get`. 

Alternatively they could be imported by cloning the repo and importing the file. This solution is not ideal since versions of the cloned repo and the package retrieved with pub get would not be guaranteed to be in sync.

## Phase 2
Sass support with the knowledge of pub package URIs is coming when running in "Dart Mode". https://github.com/sass/dart-sass/issues/19 I am currently investigating if the pre 1.0 release of Dart Sass supports all of the features exercised with our scss files. Once we have full support, we can release the scss files in the pub package and users should be able to import the scss files with package URIs.

**Comment by TedSander** [comment]
+1 I think getting the Sass files out there is beneficial even if the experience isn't great in using them. Right now people are largely in the dark with regards to how it is working, and the direction. Even if they can't use it they can at least see what is going on.

**Comment by c4wrd** [comment]
@nshahan Are there any updates on this? I am really eager towards using Dart on a few projects, specifically with this package, and this issue is a blocker for me.

**Comment by nshahan** [comment]
Thanks for the ping. It is a good reminder that I should at least push the .scss files containing the functions and constants that are used across all components. I focus on getting that done.

Most of this work got put to the side as I have been working on reorganizing our internal repo to support better syncing with github. I've spent some time trying to get the sass compiled when running `pub build` but that isn't working yet with the dart sass transformer.

**Comment by zoechi** [comment]
Also sass/dart-sass#19 was fixed recently.

**Comment by hourliert** [comment]
Hi,

First, thanks for the awesome work with dart, angular2 and angular_components 🎯.

I would like to know if there are any update on this?

Thanks in advance! 🎉

**Comment by nshahan** [comment]
I am going to be adding all of our `.scss` files to the repo soon as a reference. They not going to be used in the BUILD process yet but they are used in a separate part of our export to generate the `.css` files that we are currently shipping. 

After that we can work on getting them used as part of the build process and we can removed pre-generated `.css` files from the package.

**Comment by nshahan** [comment]
Oh hey... this is done and working. I forgot to close the issue. Some instructions to get started are in the [README](https://github.com/dart-lang/angular_components#custom-component-styles).
